import re

import pytest
from uqbar.strings import normalize

from damnation.layout import LayoutBox
from damnation.renderer import render
from damnation.style import Length, Node, Style


def parse_data(data):
    style_entries = {}
    expected_lines = []
    for line in normalize(data).splitlines():
        left, _, right = line.partition(" |")
        if right.startswith(" "):
            right = right[1:]
        expected_lines.append(right.ljust(6))
        style_entry = left.strip()
        if not style_entry:
            continue
        key, value = [_.strip() for _ in style_entry.strip(";").split(":")]
        key = key.replace("-", "_")
        if re.match("[a-z][a-z-]+", value):
            pass
        elif value.endswith("%"):
            value = Length(float(value.strip("%")), "percent")
        else:
            value = float(value)
        style_entries[key] = value
    style = Style(**style_entries)
    expected = "\n".join(expected_lines)
    return style, expected


@pytest.mark.parametrize(
    "style, expected",
    [
        parse_data(data)
        for data in [
            """
            display: block;     | ......
                                | ......
                                | ......
                                | ......
                                | ......
                                | ......
            """,
            """
            border-width: 1;    | ╭────╮
            display: block;     | ╰────╯
                                | ......
                                | ......
                                | ......
                                | ......
            """,
            """
            border-width: 1;    | ╭──╮..
            display: block;     | │  │..
            height: 2;          | │  │..
            width: 2;           | ╰──╯..
                                | ......
                                | ......
            """,
            """
            display: block;     |    ...
            height: 1;          | ......
            width: 50%;         | ......
                                | ......
                                | ......
                                | ......
            """,
            """
            border-width: 1;    | ╭───╮.
            display: block;     | │   │.
            height: 1;          | ╰───╯.
            width: 50%;         | ......
                                | ......
                                | ......
            """,
            """
            display: block;     | ......
            margin: 1;          | ......
                                | ......
                                | ......
                                | ......
                                | ......
            """,
            """
            display: block;     |
            padding: 1;         |
                                | ......
                                | ......
                                | ......
                                | ......
            """,
            """
            display: block;     | ......
            margin: 1;          | .    .
            padding: 1;         | .    .
                                | ......
                                | ......
                                | ......
            """,
            """
            border-width: 1;    | ......
            display: block;     | .╭──╮.
            margin: 1;          | .│  │.
            padding: 1;         | .│  │.
                                | .╰──╯.
                                | ......
            """,
            """
            border-width: 1;    | ......
            display: block;     | ......
            position: absolute; | ......
                                | ......
                                | ......
                                | ......
            """,
            """
            border-width: 1;    | ......
            bottom: 0;          | ......
            display: block;     | ......
            position: absolute; | ......
                                | ......
                                | ......
            """,
        ]
    ],
)
def test(style, expected):
    dummy = Node(name="box", style=style)
    root_box = LayoutBox.layout_tree(dummy, 6, 6)
    assert render(root_box, 6, 6, default_fill=".") == expected, style
